const seedJobs = [
  {
    jobTitle: "Software Development Engineer",
    datePublished: "2023-08-27T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Amazon",
    contingency: "No",
    locationFull: "TN-Nashville ; TX-Austin ; WA-Seattle",
    url: "https://www.amazon.jobs/en/jobs/2229899/software-development-engineer",
    perks: "remotefriendly ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2",
    seniority: "Mid Level",
    senioritySlug: "mid-level",
    functionalArea: "Engineering",
    functionalAreaSlug: "engineering",
  },
  {
    jobTitle: "Security Architect",
    datePublished: "2023-08-03T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "American Tower Corporation",
    contingency: "No",
    locationFull: "MA-Other",
    url: "https://www.americantower.com/",
    perks: "unlimitedvacation ; latinxintech ; womenintecherg",
    seniority: "Senior Level",
    senioritySlug: "senior-level",
    functionalArea: "IT & Cybersecurity",
    functionalAreaSlug: "it-cybersecurity",
  },
  {
    jobTitle: "Director of Product Management, Growth and Adoption",
    datePublished: "2023-08-23T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Asana",
    contingency: "No",
    locationFull: "CA-San Francisco",
    url: "https://boards.greenhouse.io/asana?gh_src=77d2661c1us",
    perks: "remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2",
    seniority: "Management",
    senioritySlug: "z-management",
    functionalArea: "Product",
    functionalAreaSlug: "product",
  },
  {
    jobTitle: "Director of Product Management, Orchestrate",
    datePublished: "2023-08-23T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Asana",
    contingency: "No",
    locationFull: "CA-San Francisco",
    url: "https://boards.greenhouse.io/asana?gh_src=77d2661c1us",
    perks: "remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2",
    seniority: "Senior Level",
    senioritySlug: "senior-level",
    functionalArea: "Product",
    functionalAreaSlug: "product",
  },
  {
    jobTitle: "Senior Software Engineer",
    datePublished: "2023-08-13T00:00:00.000Z",
    jobType: "Internship",
    companyName: "Asana",
    contingency: "No",
    locationFull: "IL-Chicago",
    url: "https://www.mcmaster.com/careers",
    perks: "unlimitedvacation ; latinxintech ; womenintecherg",
    seniority: "Mid Level",
    senioritySlug: "mid-level",
    functionalArea: "Engineering",
    functionalAreaSlug: "engineering",
  },
  {
    jobTitle: "Data Integration Specialist",
    datePublished: "2023-08-28T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Black Knight",
    contingency: "No",
    locationFull: "Remote ; Hybrid",
    url: "https://blackknight.wd1.myworkdayjobs.com/BKC/0/refreshFacet/318c8bb6f553100021d223d9780d30be",
    perks: "remotefriendly ; unlimitedvacation ; latinxintech ; womenintecherg ; lgbtqierg-2",
    seniority: "Mid Level",
    senioritySlug: "mid-level",
    functionalArea: "Data & Analytics",
    functionalAreaSlug: "data-analytics",
  },
  {
    jobTitle: "Lead Software Engineer - Identity (Remote)",
    datePublished: "2023-08-13T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Black Rock",
    contingency: "No",
    locationFull: "Remote",
    url: "https://newrelic.com/",
    perks: "remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2",
    seniority: "Senior Level",
    senioritySlug: "senior-level",
    functionalArea: "Engineering",
    functionalAreaSlug: "engineering",
  },
  {
    jobTitle: "Senior Android Developer",
    datePublished: "2023-08-03T00:00:00.000Z",
    jobType: "Temporary",
    companyName: "Bounteous",
    contingency: "Yes",
    locationFull: "Mexico ; Mexico-Remote",
    url: "https://www.bounteous.com",
    perks: "remotefriendly ; unlimitedvacation ; latinxintech ; womenintecherg ; lgbtqierg-2",
    seniority: "Senior Level",
    senioritySlug: "senior-level",
    functionalArea: "IT & Cybersecurity",
    functionalAreaSlug: "it-cybersecurity",
  },
  {
    jobTitle: "Sr Mobile UX/UI Designer",
    datePublished: "2023-08-30T00:00:00.000Z",
    jobType: "Internship",
    companyName: "Charles Schwab",
    contingency: "No",
    locationFull: "TX-Westlake",
    url: "https://jobs.schwabjobs.com/job/-/-/3378/33474697824",
    perks: "unlimitedvacation ; latinxintech ; womenintecherg",
    seniority: "Mid Level",
    senioritySlug: "mid-level",
    functionalArea: "Design",
    functionalAreaSlug: "design",
  },
  {
    jobTitle: "Senior Data Scientist",
    datePublished: "2023-08-20T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Cigna",
    contingency: "No",
    locationFull: "Remote ; CT-Bloomfield",
    url: "https://jobs.cigna.com/",
    perks: "remotefriendly ; unlimitedvacation ; latinxintech ; womenintecherg ; lgbtqierg-2",
    seniority: "Senior Level",
    senioritySlug: "senior-level",
    functionalArea: "Data & Analytics",
    functionalAreaSlug: "data-analytics",
  },
  {
    jobTitle: "Product Manager - Customer Engagement",
    datePublished: "2023-08-16T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Citrix",
    contingency: "No",
    locationFull: "CA-Santa Clara",
    url: "https://jobs.citrix.com/",
    perks: "remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2",
    seniority: "Management",
    senioritySlug: "z-management",
    functionalArea: "Product",
    functionalAreaSlug: "product",
  },
  {
    jobTitle: "Full Stack Software Engineer (Remote)",
    datePublished: "2023-08-19T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Clevertech",
    contingency: "No",
    locationFull: "Remote",
    url: "https://www.clevertech.biz/careers",
    perks: "unlimitedvacation ; latinxintech ; womenintecherg",
    seniority: "Mid Level",
    senioritySlug: "mid-level",
    functionalArea: "Engineering",
    functionalAreaSlug: "engineering",
  },
  {
    jobTitle: "Senior Backend Engineer",
    datePublished: "2023-08-02T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Coinbase",
    contingency: "No",
    locationFull: "Remote ; NY-New York",
    url: "https://www.coinbase.com/careers/",
    perks: "remotefriendly ; unlimitedvacation ; latinxintech ; womenintecherg ; lgbtqierg-2",
    seniority: "Senior Level",
    senioritySlug: "senior-level",
    functionalArea: "Engineering",
    functionalAreaSlug: "engineering",
  },
  {
    jobTitle: "Data Analyst II",
    datePublished: "2023-08-05T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "CureMetrix",
    contingency: "No",
    locationFull: "Remote ; CA-La Jolla",
    url: "https://curemetrix.com/careers/",
    perks: "unlimitedvacation ; latinxintech ; womenintecherg",
    seniority: "Mid Level",
    senioritySlug: "mid-level",
    functionalArea: "Data & Analytics",
    functionalAreaSlug: "data-analytics",
  },
  {
    jobTitle: "Senior DevOps Engineer",
    datePublished: "2023-08-08T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Datadog",
    contingency: "No",
    locationFull: "Remote ; NY-New York",
    url: "https://www.datadoghq.com/jobs/",
    perks: "remotefriendly ; unlimitedvacation ; latinxintech ; womenintecherg ; lgbtqierg-2",
    seniority: "Senior Level",
    senioritySlug: "senior-level",
    functionalArea: "IT & Cybersecurity",
    functionalAreaSlug: "it-cybersecurity",
  },
  {
    jobTitle: "UX Designer",
    datePublished: "2023-08-08T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Datadog",
    contingency: "No",
    locationFull: "Remote ; NY-New York",
    url: "https://www.datadoghq.com/jobs/",
    perks: "unlimitedvacation ; latinxintech ; womenintecherg",
    seniority: "Mid Level",
    senioritySlug: "mid-level",
    functionalArea: "Design",
    functionalAreaSlug: "design",
  },
  {
    jobTitle: "Machine Learning Engineer",
    datePublished: "2023-08-30T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "DoorDash",
    contingency: "No",
    locationFull: "Remote ; CA-San Francisco",
    url: "https://www.doordash.com/careers/",
    perks: "remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2",
    seniority: "Mid Level",
    senioritySlug: "mid-level",
    functionalArea: "Engineering",
    functionalAreaSlug: "engineering",
  },
  {
    jobTitle: "Software Engineer - Backend (Remote)",
    datePublished: "2023-08-27T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Dropbox",
    contingency: "No",
    locationFull: "Remote ; CA-San Francisco",
    url: "https://www.dropbox.com/jobs",
    perks: "unlimitedvacation ; latinxintech ; womenintecherg",
    seniority: "Mid Level",
    senioritySlug: "mid-level",
    functionalArea: "Engineering",
    functionalAreaSlug: "engineering",
  },
  {
    jobTitle: "Software Engineer - Frontend (Remote)",
    datePublished: "2023-08-27T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Dropbox",
    contingency: "No",
    locationFull: "Remote ; CA-San Francisco",
    url: "https://www.dropbox.com/jobs",
    perks: "unlimitedvacation ; latinxintech ; womenintecherg",
    seniority: "Mid Level",
    senioritySlug: "mid-level",
    functionalArea: "Engineering",
    functionalAreaSlug: "engineering",
  },
  {
    jobTitle: "Product Manager - Monetization (Remote)",
    datePublished: "2023-08-27T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Dropbox",
    contingency: "No",
    locationFull: "Remote ; CA-San Francisco",
    url: "https://www.dropbox.com/jobs",
    perks: "unlimitedvacation ; latinxintech ; womenintecherg",
    seniority: "Management",
    senioritySlug: "z-management",
    functionalArea: "Product",
    functionalAreaSlug: "product",
  },
  {
    jobTitle: "Software Engineer - Security (Remote)",
    datePublished: "2023-08-27T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Dropbox",
    contingency: "No",
    locationFull: "Remote ; CA-San Francisco",
    url: "https://www.dropbox.com/jobs",
    perks: "unlimitedvacation ; latinxintech ; womenintecherg",
    seniority: "Mid Level",
    senioritySlug: "mid-level",
    functionalArea: "Engineering",
    functionalAreaSlug: "engineering",
  },
  {
    jobTitle: "iOS Engineer",
    datePublished: "2023-08-16T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Duolingo",
    contingency: "No",
    locationFull: "CA-San Francisco",
    url: "https://jobs.lever.co/duolingo",
    perks: "remotefriendly ; unlimitedvacation ; latinxintech ; womenintecherg ; lgbtqierg-2",
    seniority: "Mid Level",
    senioritySlug: "mid-level",
    functionalArea: "Engineering",
    functionalAreaSlug: "engineering",
  },
  {
    jobTitle: "Machine Learning Engineer - Language Platform",
    datePublished: "2023-08-16T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Duolingo",
    contingency: "No",
    locationFull: "CA-San Francisco",
    url: "https://jobs.lever.co/duolingo",
    perks: "remotefriendly ; unlimitedvacation ; latinxintech ; womenintecherg ; lgbtqierg-2",
    seniority: "Mid Level",
    senioritySlug: "mid-level",
    functionalArea: "Engineering",
    functionalAreaSlug: "engineering",
  },
  {
    jobTitle: "Data Scientist",
    datePublished: "2023-08-16T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Duolingo",
    contingency: "No",
    locationFull: "CA-San Francisco",
    url: "https://jobs.lever.co/duolingo",
    perks: "remotefriendly ; unlimitedvacation ; latinxintech ; womenintecherg ; lgbtqierg-2",
    seniority: "Mid Level",
    senioritySlug: "mid-level",
    functionalArea: "Data & Analytics",
    functionalAreaSlug: "data-analytics",
  },
  {
    jobTitle: "Product Manager",
    datePublished: "2023-08-16T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Duolingo",
    contingency: "No",
    locationFull: "CA-San Francisco",
    url: "https://jobs.lever.co/duolingo",
    perks: "remotefriendly ; unlimitedvacation ; latinxintech ; womenintecherg ; lgbtqierg-2",
    seniority: "Management",
    senioritySlug: "z-management",
    functionalArea: "Product",
    functionalAreaSlug: "product",
  },
  {
    jobTitle: "Design Director",
    datePublished: "2023-08-25T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Etsy",
    contingency: "No",
    locationFull: "NY-Brooklyn",
    url: "https://www.etsy.com/careers/",
    perks: "remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2",
    seniority: "Management",
    senioritySlug: "z-management",
    functionalArea: "Design",
    functionalAreaSlug: "design",
  },
  {
    jobTitle: "Software Engineer - Backend (Remote)",
    datePublished: "2023-08-13T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Etsy",
    contingency: "No",
    locationFull: "Remote",
    url: "https://www.etsy.com/careers/",
    perks: "unlimitedvacation ; latinxintech ; womenintecherg ; lgbtqierg-2",
    seniority: "Mid Level",
    senioritySlug: "mid-level",
    functionalArea: "Engineering",
    functionalAreaSlug: "engineering",
  },
  {
    jobTitle: "Software Engineer - Frontend (Remote)",
    datePublished: "2023-08-13T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Etsy",
    contingency: "No",
    locationFull: "Remote",
    url: "https://www.etsy.com/careers/",
    perks: "unlimitedvacation ; latinxintech ; womenintecherg ; lgbtqierg-2",
    seniority: "Mid Level",
    senioritySlug: "mid-level",
    functionalArea: "Engineering",
    functionalAreaSlug: "engineering",
  },
  {
    jobTitle: "Director of Engineering",
    datePublished: "2023-08-13T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Etsy",
    contingency: "No",
    locationFull: "Remote",
    url: "https://www.etsy.com/careers/",
    perks: "remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2",
    seniority: "Management",
    senioritySlug: "z-management",
    functionalArea: "Engineering",
    functionalAreaSlug: "engineering",
  },
  {
    jobTitle: "Senior Product Manager",
    datePublished: "2023-08-03T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Expedia Group",
    contingency: "No",
    locationFull: "WA-Seattle",
    url: "https://lifeatexpedia.com/jobs/",
    perks: "remotefriendly ; unlimitedvacation ; latinxintech ; womenintecherg ; lgbtqierg-2",
    seniority: "Management",
    senioritySlug: "z-management",
    functionalArea: "Product",
    functionalAreaSlug: "product",
  },
  {
    jobTitle: "Software Engineer",
    datePublished: "2023-08-30T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Facebook",
    contingency: "No",
    locationFull: "WA-Seattle",
    url: "https://www.facebook.com/careers/",
    perks: "remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2",
    seniority: "Mid Level",
    senioritySlug: "mid-level",
    functionalArea: "Engineering",
    functionalAreaSlug: "engineering",
  },
  {
    jobTitle: "Product Designer",
    datePublished: "2023-08-03T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Ginkgo Bioworks",
    contingency: "No",
    locationFull: "MA-Boston",
    url: "https://www.ginkgobioworks.com/careers/",
    perks: "remotefriendly ; unlimitedvacation ; latinxintech ; womenintecherg ; lgbtqierg-2",
    seniority: "Mid Level",
    senioritySlug: "mid-level",
    functionalArea: "Design",
    functionalAreaSlug: "design",
  },
  {
    jobTitle: "Software Engineer",
    datePublished: "2023-08-05T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "GitHub",
    contingency: "No",
    locationFull: "Remote ; CA-San Francisco",
    url: "https://github.com/about/careers",
    perks: "remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2",
    seniority: "Mid Level",
    senioritySlug: "mid-level",
    functionalArea: "Engineering",
    functionalAreaSlug: "engineering",
  },
  {
    jobTitle: "Site Reliability Engineer",
    datePublished: "2023-08-02T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Google",
    contingency: "No",
    locationFull: "Remote ; CA-Mountain View",
    url: "https://careers.google.com/",
    perks: "remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2",
    seniority: "Mid Level",
    senioritySlug: "mid-level",
    functionalArea: "Engineering",
    functionalAreaSlug: "engineering",
  },
  {
    jobTitle: "Technical Program Manager",
    datePublished: "2023-08-03T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Google",
    contingency: "No",
    locationFull: "Remote ; CA-Mountain View",
    url: "https://careers.google.com/",
    perks: "remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2",
    seniority: "Management",
    senioritySlug: "z-management",
    functionalArea: "Product",
    functionalAreaSlug: "product",
  },
  {
    jobTitle: "UX Designer",
    datePublished: "2023-08-03T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Google",
    contingency: "No",
    locationFull: "Remote ; CA-Mountain View",
    url: "https://careers.google.com/",
    perks: "remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2",
    seniority: "Mid Level",
    senioritySlug: "mid-level",
    functionalArea: "Design",
    functionalAreaSlug: "design",
  },
  {
    jobTitle: "Machine Learning Engineer",
    datePublished: "2023-08-03T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Google",
    contingency: "No",
    locationFull: "Remote ; CA-Mountain View",
    url: "https://careers.google.com/",
    perks: "remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2",
    seniority: "Mid Level",
    senioritySlug: "mid-level",
    functionalArea: "Engineering",
    functionalAreaSlug: "engineering",
  },
  {
    jobTitle: "Data Analyst",
    datePublished: "2023-08-03T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Google",
    contingency: "No",
    locationFull: "Remote ; CA-Mountain View",
    url: "https://careers.google.com/",
    perks: "remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2",
    seniority: "Mid Level",
    senioritySlug: "mid-level",
    functionalArea: "Data & Analytics",
    functionalAreaSlug: "data-analytics",
  },
  {
    jobTitle: "Technical Writer",
    datePublished: "2023-08-03T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Google",
    contingency: "No",
    locationFull: "Remote ; CA-Mountain View",
    url: "https://careers.google.com/",
    perks: "remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2",
    seniority: "Mid Level",
    senioritySlug: "mid-level",
    functionalArea: "Content",
    functionalAreaSlug: "content",
  },
  {
    jobTitle: "Account Executive",
    datePublished: "2023-08-20T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "HubSpot",
    contingency: "No",
    locationFull: "Remote ; MA-Cambridge",
    url: "https://www.hubspot.com/careers/jobs",
    perks: "remotefriendly ; unlimitedvacation ; latinxintech ; womenintecherg ; lgbtqierg-2",
    seniority: "Entry Level",
    senioritySlug: "entry-level",
    functionalArea: "Sales",
    functionalAreaSlug: "sales",
  },
  {
    jobTitle: "Senior Frontend Engineer",
    datePublished: "2023-08-20T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "HubSpot",
    contingency: "No",
    locationFull: "Remote ; MA-Cambridge",
    url: "https://www.hubspot.com/careers/jobs",
    perks: "remotefriendly ; unlimitedvacation ; latinxintech ; womenintecherg ; lgbtqierg-2",
    seniority: "Senior Level",
    senioritySlug: "senior-level",
    functionalArea: "Engineering",
    functionalAreaSlug: "engineering",
  },
  {
    jobTitle: "Product Manager",
    datePublished: "2023-08-20T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "HubSpot",
    contingency: "No",
    locationFull: "Remote ; MA-Cambridge",
    url: "https://www.hubspot.com/careers/jobs",
    perks: "remotefriendly ; unlimitedvacation ; latinxintech ; womenintecherg ; lgbtqierg-2",
    seniority: "Management",
    senioritySlug: "z-management",
    functionalArea: "Product",
    functionalAreaSlug: "product",
  },
  {
    jobTitle: "Data Scientist",
    datePublished: "2023-08-20T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "HubSpot",
    contingency: "No",
    locationFull: "Remote ; MA-Cambridge",
    url: "https://www.hubspot.com/careers/jobs",
    perks: "remotefriendly ; unlimitedvacation ; latinxintech ; womenintecherg ; lgbtqierg-2",
    seniority: "Mid Level",
    senioritySlug: "mid-level",
    functionalArea: "Data & Analytics",
    functionalAreaSlug: "data-analytics",
  },
  {
    jobTitle: "UX Designer",
    datePublished: "2023-08-20T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "HubSpot",
    contingency: "No",
    locationFull: "Remote ; MA-Cambridge",
    url: "https://www.hubspot.com/careers/jobs",
    perks: "remotefriendly ; unlimitedvacation ; latinxintech ; womenintecherg ; lgbtqierg-2",
    seniority: "Mid Level",
    senioritySlug: "mid-level",
    functionalArea: "Design",
    functionalAreaSlug: "design",
  },
  {
    jobTitle: "Senior Full Stack Engineer",
    datePublished: "2023-08-03T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Indeed",
    contingency: "No",
    locationFull: "Remote ; TX-Austin",
    url: "https://www.indeed.jobs/",
    perks: "remotefriendly ; unlimitedvacation ; latinxintech ; womenintecherg ; lgbtqierg-2",
    seniority: "Senior Level",
    senioritySlug: "senior-level",
    functionalArea: "Engineering",
    functionalAreaSlug: "engineering",
  },
  {
    jobTitle: "Senior Software Engineer - Mobile",
    datePublished: "2023-08-03T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Indeed",
    contingency: "No",
    locationFull: "Remote ; TX-Austin",
    url: "https://www.indeed.jobs/",
    perks: "remotefriendly ; unlimitedvacation ; latinxintech ; womenintecherg ; lgbtqierg-2",
    seniority: "Senior Level",
    senioritySlug: "senior-level",
    functionalArea: "Engineering",
    functionalAreaSlug: "engineering",
  },
  {
    jobTitle: "Senior Software Engineer - Web",
    datePublished: "2023-08-03T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Indeed",
    contingency: "No",
    locationFull: "Remote ; TX-Austin",
    url: "https://www.indeed.jobs/",
    perks: "remotefriendly ; unlimitedvacation ; latinxintech ; womenintecherg ; lgbtqierg-2",
    seniority: "Senior Level",
    senioritySlug: "senior-level",
    functionalArea: "Engineering",
    functionalAreaSlug: "engineering",
  },
  {
    jobTitle: "Machine Learning Engineer",
    datePublished: "2023-08-03T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Indeed",
    contingency: "No",
    locationFull: "Remote ; TX-Austin",
    url: "https://www.indeed.jobs/",
    perks: "remotefriendly ; unlimitedvacation ; latinxintech ; womenintecherg ; lgbtqierg-2",
    seniority: "Mid Level",
    senioritySlug: "mid-level",
    functionalArea: "Engineering",
    functionalAreaSlug: "engineering",
  },
  {
    jobTitle: "Software Engineer - Backend",
    datePublished: "2023-08-03T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Indeed",
    contingency: "No",
    locationFull: "Remote ; TX-Austin",
    url: "https://www.indeed.jobs/",
    perks: "remotefriendly ; unlimitedvacation ; latinxintech ; womenintecherg ; lgbtqierg-2",
    seniority: "Mid Level",
    senioritySlug: "mid-level",
    functionalArea: "Engineering",
    functionalAreaSlug: "engineering",
  },
  {
    jobTitle: "Data Analyst",
    datePublished: "2023-08-03T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Indeed",
    contingency: "No",
    locationFull: "Remote ; TX-Austin",
    url: "https://www.indeed.jobs/",
    perks: "remotefriendly ; unlimitedvacation ; latinxintech ; womenintecherg ; lgbtqierg-2",
    seniority: "Mid Level",
    senioritySlug: "mid-level",
    functionalArea: "Data & Analytics",
    functionalAreaSlug: "data-analytics",
  },
  {
    jobTitle: "UX Designer",
    datePublished: "2023-08-03T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Indeed",
    contingency: "No",
    locationFull: "Remote ; TX-Austin",
    url: "https://www.indeed.jobs/",
    perks: "remotefriendly ; unlimitedvacation ; latinxintech ; womenintecherg ; lgbtqierg-2",
    seniority: "Mid Level",
    senioritySlug: "mid-level",
    functionalArea: "Design",
    functionalAreaSlug: "design",
  },
  {
    jobTitle: "Software Engineer - Frontend",
    datePublished: "2023-08-03T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Indeed",
    contingency: "No",
    locationFull: "Remote ; TX-Austin",
    url: "https://www.indeed.jobs/",
    perks: "remotefriendly ; unlimitedvacation ; latinxintech ; womenintecherg ; lgbtqierg-2",
    seniority: "Mid Level",
    senioritySlug: "mid-level",
    functionalArea: "Engineering",
    functionalAreaSlug: "engineering",
  },
  {
    jobTitle: "Senior Product Manager",
    datePublished: "2023-08-03T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Indeed",
    contingency: "No",
    locationFull: "Remote ; TX-Austin",
    url: "https://www.indeed.jobs/",
    perks: "remotefriendly ; unlimitedvacation ; latinxintech ; womenintecherg ; lgbtqierg-2",
    seniority: "Management",
    senioritySlug: "z-management",
    functionalArea: "Product",
    functionalAreaSlug: "product",
  },
  {
    jobTitle: "Software Engineer - Mobile",
    datePublished: "2023-08-03T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Indeed",
    contingency: "No",
    locationFull: "Remote ; TX-Austin",
    url: "https://www.indeed.jobs/",
    perks: "remotefriendly ; unlimitedvacation ; latinxintech ; womenintecherg ; lgbtqierg-2",
    seniority: "Mid Level",
    senioritySlug: "mid-level",
    functionalArea: "Engineering",
    functionalAreaSlug: "engineering",
  },
  {
    jobTitle: "Software Engineer - Web",
    datePublished: "2023-08-03T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Indeed",
    contingency: "No",
    locationFull: "Remote ; TX-Austin",
    url: "https://www.indeed.jobs/",
    perks: "remotefriendly ; unlimitedvacation ; latinxintech ; womenintecherg ; lgbtqierg-2",
    seniority: "Mid Level",
    senioritySlug: "mid-level",
    functionalArea: "Engineering",
    functionalAreaSlug: "engineering",
  },
  {
    jobTitle: "iOS Engineer",
    datePublished: "2023-08-03T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Indeed",
    contingency: "No",
    locationFull: "Remote ; TX-Austin",
    url: "https://www.indeed.jobs/",
    perks: "remotefriendly ; unlimitedvacation ; latinxintech ; womenintecherg ; lgbtqierg-2",
    seniority: "Mid Level",
    senioritySlug: "mid-level",
    functionalArea: "Engineering",
    functionalAreaSlug: "engineering",
  }
];

module.exports = { seedJobs };
