const seedJobs = [
  {
    jobTitle: "Software Development Engineer",
    datePublished: "2023-08-27T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Amazon",
    contingency: "No",
    locationFull: "TN-Nashville ; TX-Austin ; WA-Seattle",
    url: "https://www.amazon.jobs/en/jobs/2229899/software-development-engineer",
    perks:
      "remotefriendly ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2",
    seniority: "Mid Level",
    senioritySlug: "mid-level",
    functionalArea: "Engineering",
    functionalAreaSlug: "engineering",
  },
  {
    jobTitle: "Security Architect",
    datePublished: "2023-08-03T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "American Tower Corporation",
    contingency: "No",
    locationFull: "MA-Other",
    url: "https://www.americantower.com/",
    seniority: "Senior Level",
    senioritySlug: "senior-level",
    functionalArea: "IT & Cybersecurity",
    functionalAreaSlug: "it-cybersecurity",
    perks: "unlimitedvacation ; latinxintech ; womenintecherg",
  },
  {
    jobTitle: "Director of Product Management, Growth and Adoption",
    datePublished: "2023-08-23T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Asana",
    contingency: "No",
    locationFull: "CA-San Francisco",
    url: "https://boards.greenhouse.io/asana?gh_src=77d2661c1us",
    perks:
      "remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2",
    seniority: "Management",
    senioritySlug: "z-management",
    functionalArea: "Product",
    functionalAreaSlug: "product",
  },
  {
    jobTitle: "Director of Product Management, Orchestrate",
    datePublished: "2023-08-23T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Asana",
    contingency: "No",
    locationFull: "CA-San Francisco",
    url: "https://boards.greenhouse.io/asana?gh_src=77d2661c1us",
    perks:
      "remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2",
    seniority: "Senior Level",
    senioritySlug: "senior-level",
    functionalArea: "Product",
    functionalAreaSlug: "product",
  },
  {
    jobTitle: "Senior Software Engineer",
    datePublished: "2023-08-13T00:00:00.000Z",
    jobType: "Internship",
    companyName: "Asana",
    contingency: "No",
    locationFull: "IL-Chicago",
    url: "https://www.mcmaster.com/careers",
    seniority: "Mid Level",
    senioritySlug: "mid-level",
    functionalArea: "Engineering",
    functionalAreaSlug: "engineering",
    perks: "unlimitedvacation ; latinxintech ; womenintecherg",
  },
  {
    jobTitle: "Data Integration Specialist",
    datePublished: "2023-08-28T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Black Knight",
    contingency: "No",
    locationFull: "Remote ; Hybrid",
    url: "https://blackknight.wd1.myworkdayjobs.com/BKC/0/refreshFacet/318c8bb6f553100021d223d9780d30be",
    seniority: "Mid Level",
    senioritySlug: "mid-level",
    functionalArea: "Data & Analytics",
    functionalAreaSlug: "data-analytics",
    perks:
      "remotefriendly ; unlimitedvacation ; latinxintech ; womenintecherg ; lgbtqierg-2",
  },
  {
    jobTitle: "Lead Software Engineer - Identity (Remote)",
    datePublished: "2023-08-13T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Black Rock",
    contingency: "No",
    locationFull: "Remote",
    url: "https://newrelic.com/",
    seniority: "Senior Level",
    senioritySlug: "senior-level",
    functionalArea: "Engineering",
    functionalAreaSlug: "engineering",
    perks:
      "remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2",
  },
  {
    jobTitle: "Senior Android Developer",
    datePublished: "2023-08-03T00:00:00.000Z",
    jobType: "Temporary",
    companyName: "Bounteous",
    contingency: "Yes",
    locationFull: "Mexico ; Mexico-Remote",
    url: "https://www.bounteous.com",
    seniority: "Senior Level",
    senioritySlug: "senior-level",
    functionalArea: "IT & Cybersecurity",
    functionalAreaSlug: "it-cybersecurity",
    perks:
      "remotefriendly ; unlimitedvacation ; latinxintech ; womenintecherg ; lgbtqierg-2",
  },
  {
    jobTitle: "Sr Mobile UX/UI Designer",
    datePublished: "2023-08-30T00:00:00.000Z",
    jobType: "Internship",
    companyName: "Charles Schwab",
    contingency: "No",
    locationFull: "TX-Westlake",
    url: "https://jobs.schwabjobs.com/job/-/-/3378/33474697824",
    seniority: "Mid Level",
    senioritySlug: "mid-level",
    functionalArea: "Design",
    functionalAreaSlug: "design",
    perks: "unlimitedvacation ; latinxintech ; womenintecherg",
  },
  {
    jobTitle: "Senior Data Scientist",
    datePublished: "2023-08-20T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Cigna",
    contingency: "No",
    locationFull: "Remote ; CT-Bloomfield",
    url: "https://jobs.cigna.com/",
    seniority: "Senior Level",
    senioritySlug: "senior-level",
    functionalArea: "Data & Analytics",
    functionalAreaSlug: "data-analytics",
    perks:
      "remotefriendly ; unlimitedvacation ; latinxintech ; womenintecherg ; lgbtqierg-2",
  },
  {
    jobTitle: "Product Manager - Customer Engagement",
    datePublished: "2023-08-16T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Citrix",
    contingency: "No",
    locationFull: "CA-Santa Clara",
    url: "https://jobs.citrix.com/",
    seniority: "Management",
    senioritySlug: "z-management",
    functionalArea: "Product",
    functionalAreaSlug: "product",
    perks:
      "remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2",
  },
  {
    jobTitle: "Full Stack Software Engineer (Remote)",
    datePublished: "2023-08-19T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Clevertech",
    contingency: "No",
    locationFull: "Remote",
    url: "https://www.clevertech.biz/careers",
    seniority: "Mid Level",
    senioritySlug: "mid-level",
    functionalArea: "Engineering",
    functionalAreaSlug: "engineering",
    perks: "unlimitedvacation ; latinxintech ; womenintecherg",
  },
  {
    jobTitle: "Senior Backend Engineer",
    datePublished: "2023-08-02T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Coinbase",
    contingency: "No",
    locationFull: "Remote ; NY-New York",
    url: "https://www.coinbase.com/careers/",
    seniority: "Senior Level",
    senioritySlug: "senior-level",
    functionalArea: "Engineering",
    functionalAreaSlug: "engineering",
    perks:
      "remotefriendly ; unlimitedvacation ; latinxintech ; womenintecherg ; lgbtqierg-2",
  },
  {
    jobTitle: "Data Analyst II",
    datePublished: "2023-08-05T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "CureMetrix",
    contingency: "No",
    locationFull: "Remote ; CA-La Jolla",
    url: "https://curemetrix.com/careers/",
    seniority: "Mid Level",
    senioritySlug: "mid-level",
    functionalArea: "Data & Analytics",
    functionalAreaSlug: "data-analytics",
    perks: "unlimitedvacation ; latinxintech ; womenintecherg",
  },
  {
    jobTitle: "Senior DevOps Engineer",
    datePublished: "2023-08-08T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Datadog",
    contingency: "No",
    locationFull: "Remote ; NY-New York",
    url: "https://www.datadoghq.com/jobs/",
    seniority: "Senior Level",
    senioritySlug: "senior-level",
    functionalArea: "IT & Cybersecurity",
    functionalAreaSlug: "it-cybersecurity",
    perks:
      "remotefriendly ; unlimitedvacation ; latinxintech ; womenintecherg ; lgbtqierg-2",
  },
  {
    jobTitle: "UX Designer",
    datePublished: "2023-08-08T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Datadog",
    contingency: "No",
    locationFull: "Remote ; NY-New York",
    url: "https://www.datadoghq.com/jobs/",
    seniority: "Mid Level",
    senioritySlug: "mid-level",
    functionalArea: "Design",
    functionalAreaSlug: "design",
    perks: "unlimitedvacation ; latinxintech ; womenintecherg",
  },
  {
    jobTitle: "Machine Learning Engineer",
    datePublished: "2023-08-30T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "DoorDash",
    contingency: "No",
    locationFull: "Remote ; CA-San Francisco",
    url: "https://www.doordash.com/careers/",
    seniority: "Mid Level",
    senioritySlug: "mid-level",
    functionalArea: "Engineering",
    functionalAreaSlug: "engineering",
    perks:
      "remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2",
  },
  {
    jobTitle: "Software Engineer - Backend (Remote)",
    datePublished: "2023-08-27T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Dropbox",
    contingency: "No",
    locationFull: "Remote ; CA-San Francisco",
    url: "https://www.dropbox.com/jobs",
    seniority: "Mid Level",
    senioritySlug: "mid-level",
    functionalArea: "Engineering",
    functionalAreaSlug: "engineering",
    perks: "unlimitedvacation ; latinxintech ; womenintecherg",
  },
  {
    jobTitle: "Software Engineer - Frontend (Remote)",
    datePublished: "2023-08-27T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Dropbox",
    contingency: "No",
    locationFull: "Remote ; CA-San Francisco",
    url: "https://www.dropbox.com/jobs",
    seniority: "Mid Level",
    senioritySlug: "mid-level",
    functionalArea: "Engineering",
    functionalAreaSlug: "engineering",
    perks: "unlimitedvacation ; latinxintech ; womenintecherg",
  },
  {
    jobTitle: "Senior Cloud Solutions Architect (Remote)",
    datePublished: "2023-08-30T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Duo Security",
    contingency: "No",
    locationFull: "Remote ; MI-Ann Arbor",
    url: "https://careers.duo.com/jobs",
    seniority: "Senior Level",
    senioritySlug: "senior-level",
    functionalArea: "IT & Cybersecurity",
    functionalAreaSlug: "it-cybersecurity",
    perks:
      "remotefriendly ; unlimitedvacation ; latinxintech ; womenintecherg ; lgbtqierg-2",
  },
  {
    jobTitle: "Software Development Engineer - New Grad",
    datePublished: "2023-08-24T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Expedia Group",
    contingency: "No",
    locationFull: "WA-Seattle",
    url: "https://lifeatexpediagroup.com/jobs",
    seniority: "Entry Level",
    senioritySlug: "entry-level",
    functionalArea: "Engineering",
    functionalAreaSlug: "engineering",
    perks:
      "remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2",
  },
  {
    jobTitle: "Machine Learning Engineer - New Grad",
    datePublished: "2023-08-24T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Expedia Group",
    contingency: "No",
    locationFull: "WA-Seattle",
    url: "https://lifeatexpediagroup.com/jobs",
    seniority: "Entry Level",
    senioritySlug: "entry-level",
    functionalArea: "Engineering",
    functionalAreaSlug: "engineering",
    perks: "unlimitedvacation ; latinxintech ; womenintecherg",
  },
  {
    jobTitle: "Senior Software Engineer - Infrastructure",
    datePublished: "2023-08-12T00:00:00.000Z",
    jobType: "Freelance",
    companyName: "Chronosphere",
    contingency: "Yes",
    locationFull: "Remote",
    url: "https://chronosphere.io/",
    seniority: "Mid Level",
    senioritySlug: "mid-level",
    functionalArea: "Engineering",
    functionalAreaSlug: "engineering",
    perks: "",
  },
  {
    jobTitle: "Mobile App Product Manager",
    datePublished: "2023-08-19T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Common Sense Media",
    contingency: "No",
    locationFull: "Remote",
    url: "http://www.commonsensemedia.org",
    seniority: "Mid Level",
    senioritySlug: "mid-level",
    functionalArea: "Engineering",
    functionalAreaSlug: "engineering",
    perks: "",
  },
  {
    jobTitle: "Nonprofit Success Manager",
    datePublished: "2023-08-14T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Community First Foundation",
    contingency: "No",
    locationFull: "Hybrid ; CO-Denver",
    url: "https://www.communityfirstfoundation.org/",
    seniority: "Mid Level",
    senioritySlug: "mid-level",
    functionalArea: "Support",
    functionalAreaSlug: "support",
    perks: "",
  },
  {
    jobTitle: "Senior Technical Writer",
    datePublished: "2023-08-14T00:00:00.000Z",
    jobType: "Temporary",
    companyName: "CrowdStrike",
    contingency: "Yes",
    locationFull: "Remote",
    url: "https://www.crowdstrike.com/careers/",
    seniority: "Junior Level",
    senioritySlug: "entry-level",
    functionalArea: "Product",
    functionalAreaSlug: "product",
    perks: "remotefriendly ; paidparentalleave",
  },
  {
    jobTitle: "Senior Software Engineer - Frontend",
    datePublished: "2023-08-14T00:00:00.000Z",
    jobType: "Freelance",
    companyName: "CrowdStrike",
    contingency: "Yes",
    locationFull: "Remote",
    url: "https://www.crowdstrike.com/careers/",
    seniority: "Mid Level",
    senioritySlug: "mid-level",
    functionalArea: "Engineering",
    functionalAreaSlug: "engineering",
    perks: "remotefriendly ; paidparentalleave",
  },
  {
    jobTitle: "Head of Corporate Communications",
    datePublished: "2023-08-14T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "CrowdStrike",
    contingency: "No",
    locationFull: "Remote",
    url: "https://www.crowdstrike.com/careers/",
    seniority: "Management",
    senioritySlug: "z-management",
    functionalArea: "Marketing",
    functionalAreaSlug: "marketing",
    perks: "remotefriendly ; paidparentalleave",
  },
  {
    jobTitle: "Sr Manager GTM G&A Talent Team",
    datePublished: "2023-08-14T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "CrowdStrike",
    contingency: "No",
    locationFull: "Remote",
    url: "https://www.crowdstrike.com/careers/",
    seniority: "Mid Level",
    senioritySlug: "mid-level",
    functionalArea: "People Ops",
    functionalAreaSlug: "people-ops",
    perks: "remotefriendly ; paidparentalleave",
  },
  {
    jobTitle: "Product Marketing Manager",
    datePublished: "2023-08-23T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Discord",
    contingency: "No",
    locationFull: "Remote",
    url: "https://discord.com/careers",
    seniority: "Mid Level",
    senioritySlug: "mid-level",
    functionalArea: "Marketing",
    functionalAreaSlug: "marketing",
    perks: "remotefriendly ; paidparentalleave ; womenintecherg ; lgbtqierg-2",
  },
  {
    jobTitle: "Customer Solutions Engineer",
    datePublished: "2023-08-14T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Discord",
    contingency: "No",
    locationFull: "Remote",
    url: "https://discord.com/careers",
    seniority: "Mid Level",
    senioritySlug: "mid-level",
    functionalArea: "Other",
    functionalAreaSlug: "zother",
    perks: "remotefriendly ; paidparentalleave ; womenintecherg ; lgbtqierg-2",
  },
  {
    jobTitle: "Data Scientist",
    datePublished: "2023-09-15T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Tech Innovators Inc.",
    contingency: "No",
    locationFull: "CA-San Francisco",
    url: "https://techinnovators.com/careers",
    seniority: "Mid Level",
    senioritySlug: "mid-level",
    functionalArea: "Data Science",
    functionalAreaSlug: "data-science",
    perks: "unlimitedvacation ; remoteok ; datasciencerg",
  },
  {
    jobTitle: "UX Designer",
    datePublished: "2023-09-14T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "DesignTech Solutions",
    contingency: "No",
    locationFull: "NY-New York City",
    url: "https://designtechsolutions.com/careers",
    seniority: "Mid Level",
    senioritySlug: "mid-level",
    functionalArea: "Design",
    functionalAreaSlug: "design",
    perks: "unlimitedvacation ; remoteok ; designerg",
  },
  {
    jobTitle: "Financial Analyst",
    datePublished: "2023-09-13T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "Finance Pros LLC",
    contingency: "No",
    locationFull: "TX-Houston",
    url: "https://financepros.com/careers",
    seniority: "Junior Level",
    senioritySlug: "junior-level",
    functionalArea: "Finance",
    functionalAreaSlug: "finance",
    perks: "unlimitedvacation ; financeerg",
  },
  {
    jobTitle: "Marketing Specialist",
    datePublished: "2023-09-12T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "MarketMasters Inc.",
    contingency: "No",
    locationFull: "IL-Chicago",
    url: "https://marketmasters.com/careers",
    seniority: "Mid Level",
    senioritySlug: "mid-level",
    functionalArea: "Marketing",
    functionalAreaSlug: "marketing",
    perks: "unlimitedvacation ; marketingerg",
  },
  {
    jobTitle: "Network Engineer",
    datePublished: "2023-09-11T00:00:00.000Z",
    jobType: "Full Time",
    companyName: "NetConnect Solutions",
    contingency: "No",
    locationFull: "TX-Austin",
    url: "https://netconnectsolutions.com/careers",
    seniority: "Senior Level",
    senioritySlug: "senior-level",
    functionalArea: "IT & Networking",
    functionalAreaSlug: "it-networking",
    perks: "unlimitedvacation ; remoteok ; networkingerg",
  },
];

module.exports = { seedJobs };
